variables:
  IMAGE_NAME: "docker-debian-repository"
  REGISTRY_IMAGE: "$PRIVATE_REGISTRY/$IMAGE_NAME"
  VERSION: "v1"
  DOCKER_VERSION: "20.10.21"
  DIND_VERSION: $DOCKER_VERSION'-dind'
  BUILDX_IMAGE: "gitlab-registry.docker.local/docker_images/buildx:latest"
  BUILDER_IMAGE: "${IMAGE_NAME}-builder-$CI_CONCURRENT_ID"

image: docker:$DOCKER_VERSION

stages:
  - linting
  - build
  - publish

# before_script:
#   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

hadolint:
  stage: linting
  image: registry.gitlab.com/pipeline-components/hadolint:latest
  script:
    - hadolint Dockerfile
  allow_failure: true
  rules:
    - changes:
      - Dockerfile
  # when: manual

build_image:
  stage: build
  image: $BUILDX_IMAGE
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker buildx create --use --name ${BUILDER_IMAGE} --config=buildkitd.toml
    # - docker buildx build --push --progress plain -f Dockerfile --platform linux/arm/v7 -t ${REGISTRY_IMAGE}:${VERSION}-armv7 .
    # - docker buildx build --push --progress plain -f Dockerfile --platform linux/arm64 -t ${REGISTRY_IMAGE}:${VERSION}-arm64 .
    - docker buildx bake --load --file package_bake.hcl --progress plain
    # - docker manifest create $REGISTRY_IMAGE:${VERSION} --amend $REGISTRY_IMAGE:${VERSION}-armv7 --amend $REGISTRY_IMAGE:${VERSION}-arm64
  # rules:
  #   - changes:
  #     - .gitlab-ci.yml
  #     - package_bake.hcl
  #     - build_publish.sh
  # when: manual
  after_script:
    - docker buildx stop ${BUILDER_IMAGE}
    - docker buildx rm ${BUILDER_IMAGE}

publish_image:
  stage: publish
  image: $BUILDX_IMAGE
  script:
    - docker manifest create ${REGISTRY_IMAGE}:${VERSION} --amend ${REGISTRY_IMAGE}:${VERSION}-armv7 --amend ${REGISTRY_IMAGE}:${VERSION}-arm64
    - docker manifest push $REGISTRY_IMAGE:$VERSION
  rules: